<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class RecordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            [
                'title' => 'Introduction to Computer Science',
                'language' => 'English',
                'ddc_classification' => 'Applied Science',
                'call_number' => 'CS001.2023',
                'physical_location' => 'Circulation',
                'location_symbol' => 'CS-A1',
                'date_acquired' => Carbon::now()->subMonths(6),
                'source' => 'Purchase',
                'purchase_amount' => 45.99,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Computer Science, Programming, Technology',
                'additional_notes' => 'Latest edition with updated programming examples',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Noli Me Tangere',
                'language' => 'Filipino',
                'ddc_classification' => 'Literature',
                'call_number' => 'FIL899.2021',
                'physical_location' => 'Fiction',
                'location_symbol' => 'FIL-B2',
                'date_acquired' => Carbon::now()->subMonths(12),
                'source' => 'Donation',
                'purchase_amount' => null,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Philippine Literature, Classic Literature, Jose Rizal',
                'additional_notes' => 'Annotated edition with historical context',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mathematics for Engineers',
                'language' => 'English',
                'ddc_classification' => 'Pure Science',
                'call_number' => 'MATH510.2024',
                'physical_location' => 'Reference',
                'location_symbol' => 'REF-C3',
                'date_acquired' => Carbon::now()->subMonths(3),
                'source' => 'Purchase',
                'purchase_amount' => 89.50,
                'acquisition_status' => 'Processing',
                'subject_headings' => 'Mathematics, Engineering, Calculus, Linear Algebra',
                'additional_notes' => 'Comprehensive textbook with practice problems',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Historia de España',
                'language' => 'Spanish',
                'ddc_classification' => 'History',
                'call_number' => 'HIST946.2022',
                'physical_location' => 'Special Collections',
                'location_symbol' => 'SC-D4',
                'date_acquired' => Carbon::now()->subMonths(8),
                'source' => 'Exchange',
                'purchase_amount' => null,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Spanish History, European History, Culture',
                'additional_notes' => 'Bilingual edition with maps and illustrations',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Modern Art Techniques',
                'language' => 'English',
                'ddc_classification' => 'Arts',
                'call_number' => 'ART750.2023',
                'physical_location' => 'Circulation',
                'location_symbol' => 'ART-E5',
                'date_acquired' => Carbon::now()->subMonths(4),
                'source' => 'Purchase',
                'purchase_amount' => 67.25,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Art, Painting, Drawing, Contemporary Art',
                'additional_notes' => 'Full-color illustrations and step-by-step guides',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Philippine Constitution and Government',
                'language' => 'English',
                'ddc_classification' => 'Social Sciences',
                'call_number' => 'POL342.2024',
                'physical_location' => 'Reference',
                'location_symbol' => 'REF-F6',
                'date_acquired' => Carbon::now()->subMonths(2),
                'source' => 'Government Publication',
                'purchase_amount' => null,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Philippine Politics, Constitution, Government, Law',
                'additional_notes' => 'Official government publication with amendments',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'World Religions and Philosophy',
                'language' => 'English',
                'ddc_classification' => 'Philosophy & Religion',
                'call_number' => 'REL200.2023',
                'physical_location' => 'Circulation',
                'location_symbol' => 'REL-G7',
                'date_acquired' => Carbon::now()->subMonths(7),
                'source' => 'Purchase',
                'purchase_amount' => 55.75,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Religion, Philosophy, Comparative Religion, Ethics',
                'additional_notes' => 'Comprehensive overview of major world religions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Digital Photography Basics',
                'language' => 'English',
                'ddc_classification' => 'Applied Science',
                'call_number' => 'PHOTO771.2024',
                'physical_location' => 'Multimedia',
                'location_symbol' => 'MM-H8',
                'date_acquired' => Carbon::now()->subMonths(1),
                'source' => 'Purchase',
                'purchase_amount' => 42.30,
                'acquisition_status' => 'Processing',
                'subject_headings' => 'Photography, Digital Art, Technology, Visual Arts',
                'additional_notes' => 'Includes DVD with tutorial videos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Elementary Geography of the Philippines',
                'language' => 'Filipino',
                'ddc_classification' => 'Geography',
                'call_number' => 'GEO915.2022',
                'physical_location' => 'Juvenile',
                'location_symbol' => 'JUV-I9',
                'date_acquired' => Carbon::now()->subMonths(10),
                'source' => 'Donation',
                'purchase_amount' => null,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Philippine Geography, Elementary Education, Maps',
                'additional_notes' => 'Colorful maps and illustrations for young readers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Business Management Principles',
                'language' => 'English',
                'ddc_classification' => 'Social Sciences',
                'call_number' => 'BUS658.2024',
                'physical_location' => 'Circulation',
                'location_symbol' => 'BUS-J1',
                'date_acquired' => Carbon::now()->subWeeks(3),
                'source' => 'Purchase',
                'purchase_amount' => 78.95,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Business, Management, Leadership, Entrepreneurship',
                'additional_notes' => 'Case studies from successful Filipino businesses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cooking Traditional Filipino Dishes',
                'language' => 'English',
                'ddc_classification' => 'Applied Science',
                'call_number' => 'COOK641.2023',
                'physical_location' => 'Circulation',
                'location_symbol' => 'COOK-K2',
                'date_acquired' => Carbon::now()->subMonths(5),
                'source' => 'Purchase',
                'purchase_amount' => 34.50,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Cooking, Filipino Cuisine, Traditional Recipes, Food',
                'additional_notes' => 'Full-color photographs and ingredient guides',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Medical Terminology Handbook',
                'language' => 'English',
                'ddc_classification' => 'Applied Science',
                'call_number' => 'MED610.2024',
                'physical_location' => 'Reference',
                'location_symbol' => 'REF-L3',
                'date_acquired' => Carbon::now()->subWeeks(2),
                'source' => 'Purchase',
                'purchase_amount' => 125.00,
                'acquisition_status' => 'Processing',
                'subject_headings' => 'Medicine, Medical Terms, Healthcare, Anatomy',
                'additional_notes' => 'Essential reference for medical students',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Children\'s Stories from Around the World',
                'language' => 'English',
                'ddc_classification' => 'Literature',
                'call_number' => 'CHILD398.2023',
                'physical_location' => 'Juvenile',
                'location_symbol' => 'JUV-M4',
                'date_acquired' => Carbon::now()->subMonths(9),
                'source' => 'Donation',
                'purchase_amount' => null,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Children\'s Literature, Folk Tales, International Stories',
                'additional_notes' => 'Beautifully illustrated collection of global stories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Environmental Science Today',
                'language' => 'English',
                'ddc_classification' => 'Pure Science',
                'call_number' => 'ENV577.2024',
                'physical_location' => 'Circulation',
                'location_symbol' => 'ENV-N5',
                'date_acquired' => Carbon::now()->subWeeks(4),
                'source' => 'Purchase',
                'purchase_amount' => 92.40,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Environmental Science, Ecology, Climate Change, Conservation',
                'additional_notes' => 'Updated with latest climate research and data',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Music Theory Fundamentals',
                'language' => 'English',
                'ddc_classification' => 'Arts',
                'call_number' => 'MUS781.2023',
                'physical_location' => 'Multimedia',
                'location_symbol' => 'MM-O6',
                'date_acquired' => Carbon::now()->subMonths(6),
                'source' => 'Purchase',
                'purchase_amount' => 58.75,
                'acquisition_status' => 'Available',
                'subject_headings' => 'Music, Music Theory, Composition, Harmony',
                'additional_notes' => 'Includes audio CD with musical examples',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('records')->insert($records);
    }
}
